name: deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Tailwind
        run: |
          curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64
          chmod +x tailwindcss-linux-x64
          mv tailwindcss-linux-x64 tailwindcss

      - name: Build
        run: |
          ./tailwindcss -i style.css -o output.css
          rm tailwindcss

          # Additional unnecessary files to remove
          rm README.md tailwind.config.js

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: .

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    # TODO: is this necessary?
    #environment:
    #  name: github-pages
    #  url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
